kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-{{ .Release.Name }}
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.storage.capacity }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.postgres.storage.path }}