apiVersion: v1
kind: Service
metadata:
  name: postgres-service-{{ .Release.Name }}
  labels:
    app: postgres
spec:
  ports:
   - port: {{ .Values.postgres.statefulset.port }}
  selector:
   app: postgres