{{- if .Values.dockerSecret.enabled -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerSecret.secret }}
kind: Secret
metadata:
  name: {{ .Values.dockerSecret.name }}
type: kubernetes.io/dockerconfigjson
{{- end}}