apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-{{ .Release.Name }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgres.config.dbName }}
  POSTGRES_USER: {{ .Values.postgres.config.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.postgres.config.dbPass }}
