apiVersion: v1
kind: Service
metadata:
  name: sfapp-service-{{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: sfapp
  ports:
  - port: {{ .Values.sfapp.service.port }}
    targetPort: {{ .Values.sfapp.deployment.port }}
    nodePort: {{ .Values.sfapp.service.nodeport }}