dockerSecret:
  enabled: false
  name:
  secret:


postgres:

  config:
    dbName:
    dbUser:
    dbPass:

  storage:
    capacity: 5Gi
    path: "/mnt/data"

  statefulset:
    replicas: 1
    image: mirror.gcr.io/postgres:13-alpine
    port: 5432
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
      pvclaim:
        capacity: 5Gi


sfapp:
  service:
    port: 80
    nodeport: 30000

  deployment:
    replicas: 1
    image:
    port: 3003
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"

